<?php

/**
 * @file
 * File contains JS float block initialization.
 *
 * The module loads all needed libraries for initializing jQuery UI dialog
 * library as well as jQuery.cookies plugin to remember the block position.
 */

/**
 * Implements hook_menu().
 */
function masquerade_float_block_menu() {
  $items = array();
  $masquerade_menu = masquerade_menu();
  $admin_item = $masquerade_menu['admin/config/people/masquerade'];
  // Use the same permissions as for Masquerade module configuration.
  $items['admin/config/people/masquerade/float-block'] = array(
    'title'            => 'Float block',
    'description'      => 'Enable/disable Masquerade float block',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('masquerade_float_block_admin_page_form'),
    'type'             => MENU_LOCAL_TASK,
    'access arguments' => $admin_item['access arguments'],
    'file'             => 'masquerade_float_block.admin.inc',
    'weight'           => 1,
  );
  $items['admin/config/people/masquerade/settings'] = array(
    'title'       => 'Masquerade settings',
    'description' => 'Enable/disable Masquerade float block',
    'type'        => MENU_DEFAULT_LOCAL_TASK,
    'weight'      => 0,
  );

  return $items;
}

/**
 * Implements hook_page_attachments_alter().
 */
function masquerade_float_block_page_attachments_alter(array &$page) {
  $masquerade_float_block_settings = \Drupal::configFactory()->getEditable('masquerade_float_block.settings');

  if (isset($_GET['mfb_show'])) {
    if (in_array($_GET['mfb_show'], array(1, 0))) {
      $masquerade_float_block_settings->set('visible', $_GET['mfb_show']);
      $masquerade_float_block_settings->save();
    }
    else {
      drupal_set_message(t('Incorrect mfb_show parameter value: only 1 or 0 possible.'), 'error');
    }
  }

  $visible = $masquerade_float_block_settings->get('visible');

  if ($visible) {
    // Get the "Masquerade" form errors.
    //$form_errors = FormStateInterface::getErrors(); // ? how to load form errors.
    $errors = '';
    if (isset($form_errors['masquerade_user_field'])) {
      // Clean up the messages from the main screen and add them to the block.
      //form_clear_error();
      drupal_get_messages('error');
      $errors = '<div class="messages error">' . $form_errors['masquerade_user_field'] . '</div>';
    }


    $block_title = t('Masquerade');

    $form = \Drupal::formBuilder()->getForm('Drupal\masquerade\Form\MasqueradeForm');
    $render_service = \Drupal::service('renderer');
    $html = $render_service->renderPlain($form);

    $page['#attached']['library'][] = 'masquerade_float_block/masquerade-float-block';
    $page['#attached']['drupalSettings']['masquerade_float_block']['block']['content'] =  $errors . $html;
    $page['#attached']['drupalSettings']['masquerade_float_block']['block']['subject'] = $block_title;
  }
}

/**
 * Implements hook_help().
 */
function masquerade_float_block_help($path, $arg) {
  switch ($path) {
    case 'admin/help#masquerade_float_block':
      $output = file_get_contents(drupal_get_path('module', 'masquerade_float_block') . '/README.txt');

      return '<pre>' . check_plain($output) . '</pre>';
  }
}
