<?php

/**
 * @file
 * File contains JS float block initialization.
 *
 * TODO: Add admin UI if there this feature will be requested.
 */

/**
 * Implements hook_page_build().
 */
function masquerade_float_block_page_build(&$page) {
  $get = drupal_get_query_parameters();
  if (isset($get['mfb_show'])) {
    if (in_array($get['mfb_show'], array(1, 0))) {
      variable_set('masquerade_float_block_visible', $get['mfb_show']);
    }
    else {
      drupal_set_message(t('Incorrect mfb_show parameter value: only 1 or 0 possible.'));
    }
  }

  $masquerade_float_block_visible = variable_get('masquerade_float_block_visible', 1);

  if ($masquerade_float_block_visible) {
    $block = module_invoke('masquerade', 'block_view', 'masquerade');
    if (!empty($block)) {

      $main = &$page['content']['system_main']['main'];
      $main['#attached']['library'][] = array('system', 'drupal.ajax');
      $main['#attached']['library'][] = array('system', 'ui.dialog');
      $main['#attached']['library'][] = array('system', 'effects');
      $main['#attached']['library'][] = array('system', 'jquery.cookie');

      $block['content'] = drupal_render($block['content']);

      $data = array(
        'masquerade_float_block' => array('block' => $block),
      );

      $main['#attached']['js'][] = array('data' => $data, 'type' => 'setting');
      $js_path = drupal_get_path('module', 'masquerade_float_block') . '/masquerade_float_block.js';
      $main['#attached']['js'][$js_path] = array();
    }
  }
}
